package com.citibanamex.api.cardsmaintenance.model;

public enum CardsMaintenanceConstant {
	AFEWS_MESSAGE_ID("6004"), SOURCE_SYSTEM("CCP"), CIC_CONTROL_ID("OVCOD001"), COUNTRY_CODE("MX"), OVERRIDE_CD(
			"7"), CARDS_PRECEDING_ZEROS("000"),

	DATE_IN_DDMMYYYY_FORMAT("ddMMyyyy"), TIME_IN_HHMMSS_FORMAT("HHmmss"), TIME_IN_MSSSSSSS_FORMAT(
			"msssssss"), DATE_PATTERN_FOR_VALIDATION("\\d{2}\\d{2}\\d{4}"),

	CRUD_INDICATOR_LOCKED("L"), CRUD_INDICATOR_UNLOCKED("U"), CRUD_INDICATOR_INQUIRY("I"), BACKEND_LOCKED_INDICATOR("Y"),
	BACKEND_UNLOCKED_INDICATOR("N"), BACKEND_NEITHER_LOCK_NOR_UNLOCK_INDICATOR("U"), BACKEND_SUCCESSFULL_OPERATION_RETURN_CODE("00"),
	BACKEND_UNSUCCESSFULL_OPERATION_RETURN_CODE("02"), BACKEND_UNSUCCESSFULL_OPERATION_REASON_CODE_FOR_LOCK("20001"),
	BACKEND_UNSUCCESSFULL_OPERATION_REASON_CODE_FOR_UNLOCK("20003"),
	
	BLOCKED_CARD_STATUS("BLOCKED"), UNBLOCKED_CARD_STATUS("UNBLOCKED"), BLOCKED_CARD_STATUS_WITH_DIFFERENT_OVERRIDE_CODE(
	"CARD_HAS_ALREADY_AN_ACTIVE_OVERRIDE_CODE_OTHER_THAN_7"), ALREADY_BLOCKED_CARD_STATUS("CARD IS ALREADY IN BLOCKED STATUS"),
	ALREADY_UNBLOCKED_CARD_STATUS("CARD IS ALREADY IN UNBLOCKED STATUS");

	private String value;

	private CardsMaintenanceConstant(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

}
